name: Cypress End to End
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ staging, main ]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: 'test'
      APOLLO_CLIENT_URI: ${{ secrets.APOLLO_CLIENT_URI }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_AUTH_PROVIDER: ${{ secrets.FIREBASE_SERVICE_AUTH_PROVIDER }}
      FIREBASE_SERVICE_AUTH_URI: ${{ secrets.FIREBASE_SERVICE_AUTH_URI }}
      FIREBASE_SERVICE_CLIENT_CERT: ${{ secrets.FIREBASE_SERVICE_CLIENT_CERT }}
      FIREBASE_SERVICE_CLIENT_EMAIL: ${{ secrets.FIREBASE_SERVICE_CLIENT_EMAIL }}
      FIREBASE_SERVICE_CLIENT_ID: ${{ secrets.FIREBASE_SERVICE_CLIENT_ID }}
      FIREBASE_SERVICE_PRIVATE_KEY: ${{ secrets.FIREBASE_SERVICE_PRIVATE_KEY }}
      FIREBASE_SERVICE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_SERVICE_PRIVATE_KEY_ID }}
      FIREBASE_SERVICE_PROJECT_ID: ${{ secrets.FIREBASE_SERVICE_PROJECT_ID }}
      FIREBASE_SERVICE_TOKEN_URI: ${{ secrets.FIREBASE_SERVICE_TOKEN_URI }}
      FIREBASE_SERVICE_TYPE: ${{ secrets.FIREBASE_SERVICE_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn run test-start
          wait-on: 'http://localhost:1234'
          wait-on-timeout: 240
          command: yarn cypress:test
      - name: Test Reporting
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 15209625f8fdc65004f9124c0c8ea306cf5526f80d3fb79874f302684f06c0b2