name: Cypress End to End
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      APOLLO_CLIENT_URI: ${{ secrets.APOLLO_CLIENT_URI }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn run test-start
          wait-on: 'http://localhost:1234'
          wait-on-timeout: 240
          command: yarn cypress:coverage
      - name: Test Reporting
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 15209625f8fdc65004f9124c0c8ea306cf5526f80d3fb79874f302684f06c0b2